### ISSUE TITLE
netcfginstanceid registry value failed

### ISSUE THREAD

**Issue by RDisOP** [OpenVPN/openvpn-build#263] opened 2022-08-13 06:48 UTC
i keep getting this error when installing openvpn on windows 11

**Comment by flichtenheld** [comment] 2022-12-12 12:24
Please tell us which version of the installer you tested this with. Also please try the latest 2.6 Beta release.

**Comment by flichtenheld** [comment] 2024-03-06 15:48
No answer. Probably a duplicate of #200 anyway.

**Closed by flichtenheld** 2024-03-06 15:48 UTC
Labels: needsmoreinfo
