### ISSUE TITLE
2.6.3 Problem With TAP Driver Signature

### ISSUE THREAD

**Issue by r4taw2mg** [OpenVPN/openvpn-build#365] opened 2023-04-30 11:59 UTC
Hi, I was just trying to install 2.6.3 MSI on Windows 7 (updating from 2.6.0). While trying to install the TAP-Windows6 driver I receive an error message that the driver has no valid digital signature. Being careful, I aborted the installation. Is there a problem with the installer?

**Comment by lstipakov** [comment] 2023-04-30 15:42
Hi, thanks for reporting it. You can proceed with installation, if you check the driver version it should be be 9.24.6. I'll check signing part.

**Comment by cron2** [comment] 2023-04-30 15:56
@r4taw2mg which version is that?  2.6.3-I001 or I002/I003?

**Comment by r4taw2mg** [comment] 2023-04-30 16:00
> @r4taw2mg which version is that? 2.6.3-I001 or I002/I003?

It's I003.

**Comment by lstipakov** [comment] 2023-05-01 09:31
I have rebuilt the driver packages (MSM), they now include the exact same drivers from 2.6.0. I have uploaded them to https://github.com/OpenVPN/tap-windows6/releases/tag/9.26.0, however I cannot build an installer package in GitHub Actions because of [this](https://github.com/microsoft/vcpkg/issues/31170) vcpkg bug.

**Comment by lstipakov** [comment] 2023-05-01 09:46
@r4taw2mg I have build the MSI with the new driver, could you please give it a try? 
[OpenVPN-2.6.3-I003-amd64.zip](https://github.com/OpenVPN/openvpn-build/files/11364789/OpenVPN-2.6.3-I003-amd64.zip)

**Comment by flichtenheld** [comment] 2023-05-11 11:00
Should be fixed in 2.6.4-I001. @lstipakov, @r4taw2mg can you confirm?

**Comment by flichtenheld** [comment] 2023-05-12 10:09
@lstipakov confirmed on IRC that the issue is fixed in 2.6.4.

**Closed by flichtenheld** 2023-05-12 10:09 UTC
Labels: msi, win7

**Comment by Avnsx** [comment] 2023-06-30 20:39
I'm happy you guys still try to support Windows 7!

**Comment by lstipakov** [comment] 2023-07-01 11:20
> By the way, am I still able to utilise the Data Channel Offload (DCO) kernel acceleration support for Windows if I use the operating system windows 7

No, DCO requires Windows 10 20H1 and newer.
