### ISSUE TITLE
Installation failure in custom action for OpenVPN 2.5-beta2

### ISSUE THREAD

**Issue by mattock** [OpenVPN/openvpn-build#187] opened 2020-08-28 12:06 UTC
I built OpenVPN 2.5-beta2 MSI installers today. When I tested them on my up-to-date Windows 10 64-bit laptop the installation failed with this log message:

```
WriteRegistryValues: Key: \Software\OpenVPN, Name: priority, Value: NORMAL_PRIORITY_CLASS
MSI (s) (7C:90) [12:05:08:513]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\tap0901,,BinaryType=1,,)
MSI (s) (7C:90) [12:05:08:513]: Executing op: RegAddValue(,Value=#1,)
WriteRegistryValues: Key: \SOFTWARE\tap0901, Name: , Value: #1
MSI (s) (7C:90) [12:05:08:513]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Wintun,,BinaryType=1,,)
MSI (s) (7C:90) [12:05:08:513]: Executing op: RegAddValue(,Value=#1,)
WriteRegistryValues: Key: \SOFTWARE\Wintun, Name: , Value: #1
MSI (s) (7C:90) [12:05:08:513]: Executing op: ActionStart(Name=InstallTUNTAPAdaptersRollback,,)
Action 12.05.08: InstallTUNTAPAdaptersRollback. 
MSI (s) (7C:90) [12:05:08:513]: Executing op: CustomActionSchedule(Action=InstallTUNTAPAdaptersRollback,ActionType=3329,Source=BinaryData,Target=ProcessDeferredAction,CustomActionData=x)
MSI (s) (7C:90) [12:05:08:513]: Executing op: ActionStart(Name=InstallTUNTAPAdapters,Description=Creating TUN/TAP adapters,Template=[1]: [2] [3] [4])
 ers: Creating adapter: OpenVPN Wintun Wintun 
Error 2551. OpenVPNMSICA: tap_set_adapter_name: Error renaming adapter  Error 1: Funktio ei kelpaa.
MSI (s) (7C!18) [12:05:18:209]: Product: OpenVPN 2.5-beta2-I601 amd64 -- Error 2551. OpenVPNMSICA: tap_set_adapter_name: Error renaming adapter  Error 1: Funktio ei kelpaa.

CustomAction InstallTUNTAPAdapters returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 12.05.18: InstallExecute. Return value 3.
MSI (s) (7C:90) [12:05:18:294]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (7C:90) [12:05:18:294]: User policy value 'DisableRollback' is 0
MSI (s) (7C:90) [12:05:18:294]: Machine policy value 'DisableRollback' is 0
MSI (s) (7C:90) [12:05:18:294]: Note: 1: 2318 2:  
MSI (s) (7C:90) [12:05:18:294]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1360814244,LangId=1033,Platform=589824,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (7C:90) [12:05:18:294]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (7C:90) [12:05:18:294]: Executing op: DialogInfo(Type=1,Argument=OpenVPN)
MSI (s) (7C:90) [12:05:18:294]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
```

The installer in question is this: https://build.openvpn.net/downloads/releases/OpenVPN-2.5-beta2-I601-amd64.msi

The problem manifests itself even if no tap-windows6 adapters are installed or in driver store. It also happens during upgrades (beta1->beta2).

**Comment by mattock** [comment] 2020-08-28 12:07
"Funktio ei kelpaa" means "Invalid function" or similar in english.

**Comment by mattock** [comment] 2020-08-28 12:41
This is actually not related to tap-windows6. The error gets triggered by renaming of the Wintun adapter. If I remove all Wintun adapters from the driver store I get a different error message:

```
OPENVPNMSICA: tap_create_adapter: No driver for device "Wintun" installed
```

**Comment by mattock** [comment] 2020-08-28 12:41
Also, the problem exhibits itself with 2.5-beta1, so this is not a regression.

**Comment by mattock** [comment] 2020-08-28 12:43
If I disable the Wintun driver in features I _do_ get a tap-windows6 error as well:
```
OPENVPNMSICA: tap_create_adapter: No driver for device "root\tap0901" installed
```
The failures seem related to the "netsh interface set-interface" commands.

**Comment by cron2** [comment] 2020-08-28 13:23
These netsh commands come from 

commit 5b313a3565558cd1da4723c3950df227f941cf62
Author: Lev Stipakov <lev@openvpn.net>
Date:   Fri Jul 3 22:20:29 2020 +0300

    tap.c: fix adapter renaming

but seem to work for lev and others... very strange.

**Comment by TinCanTech** [comment] 2020-08-28 13:39
W10-64b: Upgrade beta1 -> beta2 OK, Uninstall/re-install OK

**Comment by mattock** [comment] 2020-08-31 12:55
Some vague logic is beginning to form here. Installation of wintun and tap-windows6 causes the following registry keys to be created:

* HKLM:\SOFTWARE\wintun
* HKLM:\SOFTWARE\tap0901

There entries get created _even if the installation fails_. Their contents look like this:
```
PS HKLM:\SOFTWARE> get-itemproperty wintun


InstallerHash      : FB1CD5E7C3EA30DFAFD3CC1862E311388361D896610DB28C63716DA9D71E8F3F
InstallerBuildtime : 637116623024505677
Version            : 0.8
PSPath             : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\wintun
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE
PSChildName        : wintun
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry
``` 
and 

```
PS HKLM:\SOFTWARE> get-itemproperty tap0901

InstallerHash      : DF9D71C294971E7D58811F6FCF915A08C24586BD890FDD9BF49047FA8B9F9515
InstallerBuildtime : 637341057038284852
Version            : 9.24.4
PSPath             : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\software\tap0901
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\software
PSChildName        : tap0901
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry
```
If a feature is disabled the registry key is not added.

On a successful uninstallation the registry key(s) are removed. These keys thus seem to be metadata for"installed programs" or the installers themselves. If the "wintun" feature is disabled then installation of OpenVPN + tap-windows6 succeeds consistently.

Wintun installation fails consistently with the original error message, even if starting from (apparently) clean state, that is after having removed all traces of OpenVPN, registry keys (above) and drivers from the driver store.

The failure happens _after_ the drivers have been installed to the driver store, i.e. when adding the adapters. So netsh is probably somehow to blame here.

One interesting possibly related issue is that when looking at adapter events for TAP-Windows (e.g. in Control panel) I see references to wintun as well. Looks like both Wintun and tap-windows6 get registered to ROOT\NET\0000. Perhaps this is at the root of the problems?

**Comment by selvanair** [comment] 2020-08-31 19:55
> If I disable the Wintun driver in features I _do_ get a tap-windows6 error as well:
> 
> ```
> OPENVPNMSICA: tap_create_adapter: No driver for device "root\tap0901" installed
> ```
> 
> The failures seem related to the "netsh interface set-interface" commands.

FWIW, I saw a similar error once in my numerous trials of installing and uninstalling beta1 and beta2. I did not write down the error, so not sure exactly the same or not,  but similar. The error did not go away by cleaning up with the Remove-Tapwindows.ps1 script, but a reboot "fixed" it. Unable to reproduce since.

> "Funktio ei kelpaa" means "Invalid function" or similar in english.

If its netsh that is failing, this error is not reliable as we use CreateProcess for that and what we really get back is the exit code of the process. And that is usually 1 for netsh when it fails. Treating it as a Windows error code is misleading. The actual error output of netsh is not captured by our ExecCommand().

**Comment by lstipakov** [comment] 2020-09-01 19:09
For comparison, here is my log (where installation works):
```

WriteRegistryValues: Key: \Software\OpenVPN, Name: priority, Value: NORMAL_PRIORITY_CLASS
MSI (s) (58:10) [22:01:49:135]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\tap0901,,BinaryType=1,,)
MSI (s) (58:10) [22:01:49:135]: Executing op: RegAddValue(,Value=#1,)
WriteRegistryValues: Key: \SOFTWARE\tap0901, Name: , Value: #1
MSI (s) (58:10) [22:01:49:136]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Wintun,,BinaryType=1,,)
MSI (s) (58:10) [22:01:49:136]: Executing op: RegAddValue(,Value=#1,)
WriteRegistryValues: Key: \SOFTWARE\Wintun, Name: , Value: #1
MSI (s) (58:10) [22:01:49:136]: Executing op: ActionStart(Name=InstallTUNTAPAdaptersRollback,,)
Action 22.01.49: InstallTUNTAPAdaptersRollback. 
MSI (s) (58:10) [22:01:49:137]: Executing op: CustomActionSchedule(Action=InstallTUNTAPAdaptersRollback,ActionType=3329,Source=BinaryData,Target=ProcessDeferredAction,CustomActionData=x)
MSI (s) (58:10) [22:01:49:137]: Executing op: ActionStart(Name=InstallTUNTAPAdapters,Description=Creating TUN/TAP adapters,Template=[1]: [2] [3] [4])
Action 22.01.49: InstallTUNTAPAdapters. Creating TUN/TAP adapters
MSI (s) (58:10) [22:01:49:139]: Executing op: CustomActionSchedule(Action=InstallTUNTAPAdapters,ActionType=3073,Source=BinaryData,Target=ProcessDeferredAction,CustomActionData=x create="OpenVPN Wintun|Wintun" create="OpenVPN TAP-Windows6|root\tap0901")
MSI (s) (58:70) [22:01:49:140]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI1796.tmp, Entrypoint: ProcessDeferredAction
InstallTUNTAPAdapters: Creating adapter: OpenVPN Wintun Wintun 
InstallTUNTAPAdapters: Creating adapter: OpenVPN TAP-Windows6 root\tap0901 
MSI (s) (58:10) [22:01:55:500]: Executing op: ActionStart(Name=InstallTUNTAPAdaptersCommit,,)
Action 22.01.55: InstallTUNTAPAdaptersCommit. 
MSI (s) (58:10) [22:01:55:501]: Executing op: CustomActionSchedule(Action=InstallTUNTAPAdaptersCommit,ActionType=3585,Source=BinaryData,Target=ProcessDeferredAction,CustomActionData=x)
MSI (s) (58:10) [22:01:55:501]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
Action 22.01.55: InstallServices. Installing new services
```

**Comment by lstipakov** [comment] 2020-09-01 19:12
@rozmansi do you have any ideas what might be wrong? We surely need more logging, like netsh command line and its output,

**Comment by mattock** [comment] 2020-09-02 07:45
@lstipakov kindly provided a test installer which outputs the netsh command-line. Here are the results in my case:

* https://build.openvpn.net/downloads/temp/openvpn-build-issue-187/netsh-wintun-failure.png

**Comment by mattock** [comment] 2020-09-02 08:00
Looks like I can reproduce the problem manually in an elevated Powershell prompt:

```
PS C:\WINDOWS\system32> netsh interface set interface name="Lähiverkkoyhteys" newname="OpenVPN Wintun"
Dataa ei ole enempää.


PS C:\WINDOWS\system32> echo $LASTEXITCODE
1
```
Exits with 1. This is because "Lähiverkkoyhteys" is not present at all:

```
PS C:\WINDOWS\system32> Get-Netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Ethernet                  Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       400 Mbps
```
If I repeat the renaming process on a adapter that _is_ present things do work as expected:
```
PS C:\WINDOWS\system32> netsh interface set interface name="Ethernet" newname="Ethernet2"

PS C:\WINDOWS\system32> echo $LASTEXITCODE
0
PS C:\WINDOWS\system32> Get-Netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Ethernet2                 Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       360 Mbps
```

Wintun is present in the Driver Store:

```
PS C:\WINDOWS\system32> pnputil.exe -e|Select-string -context 3 Wireguard                                                                                                                                                                         Signer name :               Microsoft Windows Hardware Compatibility Publisher
Published name :            oem3.inf
Driver package provider :   WireGuard LLC
Class :                     Verkkosovittimet
Driver date and version :   12/10/2019 0.8.0.0
Signer name :               Microsoft Windows Hardware Compatibility Publisher  
```

If I get the adapter listing before clicking on "OK" after the netsh call in the installer has failed I see "Lähiverkkoyhteys" there:
```
PS C:\WINDOWS\system32> get-netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Lähiverkkoyhteys          Wintun Userspace Tunnel #2                   44 Disconnected                         100 Gbps
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Ethernet2                 Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       360 Mbps
```

**Comment by mattock** [comment] 2020-09-02 08:03
If I try to rename "Lähiverkkoyhteys" manually before clicking "OK" I get this (in Finnish):
```
PS C:\WINDOWS\system32> netsh interface set interface name="Lähiverkkoyhteys" newname="OpenVPN Wintun"
Yhteyttä ei muodostettu, koska verkossa on toinen samanlainen nimi. Jos olet liittymässä toimialueeseen, muuta tietokoneen nimi Ohjauspaneelin Järjestelmä-toiminnossa ja yritä sitten uudelleen. Jos olet liittymässä työryhmään, valitse toinen työryhmän nimi.

PS C:\WINDOWS\system32> get-netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Lähiverkkoyhteys          Wintun Userspace Tunnel #2                   44 Disconnected                         100 Gbps
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Ethernet2                 Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       360 Mbps
```

**Comment by lstipakov** [comment] 2020-09-02 08:26
Thanks,

That brings more questions than answers. When I try to rename adapter to the name which already exists, I got different error message:

```
C:\WINDOWS\system32>netsh interface set interface name="ÖÖpenVPN" newname="Wi-Fi"
Tiedosto on olemassa.
```

**Comment by lstipakov** [comment] 2020-09-02 08:35
Apparently in English your error message is "You were not connected because a duplicate name exists on the network.".

**Comment by lstipakov** [comment] 2020-09-02 09:00
https://social.technet.microsoft.com/Forums/azure/en-US/081bfb07-0410-4094-a77b-38f68cdf4fe9/how-to-delete-removed-network-adapters-from-the-registry-irrelevant-netsh-output?forum=winserverPN

**Comment by mattock** [comment] 2020-09-02 11:13
I let the installer run until it failed and gave the popup box (above image link). Then I ran Rename-Netadapter:
```
PS C:\WINDOWS\system32> Rename-Netadapter -Name "Lähiverkkoyhteys" -NewName "OpenVPN Wintun"
Rename-Netadapter : {Objekti on olemassa} Yritettiin luoda objekti. Objektinimi on jo olemassa.
At line:1 char:1
+ Rename-Netadapter -Name "Lähiverkkoyhteys" -NewName "OpenVPN Wintun"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (MSFT_NetAdapter...PTOP-TCJDST2N"):ROOT/StandardCimv2/MSFT_NetAdapter) [
   Rename-NetAdapter], CimException
    + FullyQualifiedErrorId : Windows System Error 698,Rename-NetAdapter
```
Translated to English: "{Object is already present} Tried to create an object. Objectname is already present."

Much better error message than what netsh gives.

**Comment by mattock** [comment] 2020-09-02 11:30
All adapters, including the hidden ones (same time as in above comment):
```
PS C:\WINDOWS\system32> Get-Netadapter -IncludeHidden

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Lähiverkkoyhteys* 11      WAN Miniport (Network Monitor)               21 Up                                      0 bps
Lähiverkkoyhteys          Wintun Userspace Tunnel #2                   44 Disconnected                         100 Gbps
Lähiverkkoyhteys* 7       WAN Miniport (PPTP)                          20 Disconnected                            0 bps
Lähiverkkoyhteys* 4       WAN Miniport (SSTP)                          19 Disconnected                            0 bps
Lähiverkkoyhteys* 10      WAN Miniport (IPv6)                          18 Up                                      0 bps
Teredo Tunneling Pseud...                                              17 Not Present                             0 bps
Lähiverkkoyhteys* 6       WAN Miniport (L2TP)                          16 Disconnected                            0 bps
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Lähiverkkoyhteys* 12      Microsoft Wi-Fi Direct Virtual Ada...#4      11 Disconnected 8A-B1-11-3C-A8-34          0 bps
Lähiverkkoyhteys* 3       Microsoft Wi-Fi Direct Virtual Ada...#3      10 Disconnected 88-B1-11-3C-A8-35          0 bps
Ethernet                  Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
Microsoft IP-HTTPS Pla...                                               8 Not Present                             0 bps
Lähiverkkoyhteys* 5       WAN Miniport (IKEv2)                          7 Disconnected                            0 bps
Ethernet (ytimen virhe... Microsoft Kernel Debug Network Adapter        6 Not Present                             0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       400 Mbps
6to4 Adapter                                                            4 Not Present                             0 bps
Lähiverkkoyhteys* 8       WAN Miniport (PPPOE)                          3 Disconnected                            0 bps
Lähiverkkoyhteys* 9       WAN Miniport (IP)                             2 Up                                      0 bps
```

**Comment by mattock** [comment] 2020-09-02 11:39
The new name is clearly the problem:
```
PS C:\Users\samul> Rename-Netadapter -Name "Lähiverkkoyhteys" -NewName "OpenVPN Wintun LOL"
PS C:\Users\samul> Get-Netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
OpenVPN Wintun LOL        Wintun Userspace Tunnel #2                   44 Disconnected                         100 Gbps
Ethernet                  Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       200 Mbps

```

**Comment by mattock** [comment] 2020-09-02 12:02
@lstipakov provided an installer which proceeds despite renaming failures. After running that I have these adapters:
```
PS HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\> Get-Netadapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Lähiverkkoyhteys 2        TAP-Windows Adapter V9                       45 Disconnected 00-FF-87-E2-26-C4         1 Gbps
Lähiverkkoyhteys          Wintun Userspace Tunnel #2                   44 Disconnected                         100 Gbps
Bluetooth-verkkoyhteys    Bluetooth Device (Personal Area Netw...      14 Disconnected 88-B1-11-3C-A8-38         3 Mbps
Ethernet                  Intel(R) Ethernet Connection (4) I219-V       9 Disconnected 54-E1-AD-59-96-E5          0 bps
WLAN                      Intel(R) Dual Band Wireless-AC 8265           5 Up           88-B1-11-3C-A8-34       400 Mbps
```

**Comment by rozmansi** [comment] 2020-09-02 12:25
> 
> 
> @lstipakov kindly provided a test installer which outputs the netsh command-line. Here are the results in my case:
> 
>     * https://build.openvpn.net/downloads/temp/openvpn-build-issue-187/netsh-wintun-failure.png

Notice the garbled characters in:
<img width="273" alt="netsh-wintun-failure" src="https://user-images.githubusercontent.com/6889694/91979871-b3d76780-ed26-11ea-91ed-69d2b42a8f5f.png">

I believe `get_reg_string()` returns string in Windows-1252 encoding (or whatever is default encoding for non-Unicode programs on Finnish Windows).

Then `_stprintf_s()` uses the code page set by `setlocale()`. Looks like the "L*ä*hiverkkoyhteys" is encoded wrong, making the netsh command line to fail.

I suppose I should revise the tapctl.exe/libopenvpnmsica.dll source code to use Unicode WCHAR strings only. Would definitely avoid a lot of confusion which strings are Windows-1252, IBM850, or UTF-8.

**Comment by lstipakov** [comment] 2020-09-02 12:29
@rozmansi it also fails when running netsh manually. 

Unfortunately renaming turned to be unreliable, so let's just remove it.

**Comment by rozmansi** [comment] 2020-09-02 12:42
Just remembered that after a new adapter is created, it takes some time for all the registry keys and values to populate.

The setup is creating adapter then immediately renaming it. Can you temporarily add a `Sleep(3000)` after `check_reboot()` in `tap_create_adapter()` and see if it stabilizes renaming?

**Comment by rozmansi** [comment] 2020-09-02 12:44
If it does, I'll add a proper registry wait loop in the `tap_create_adapter()` not to return before the adapter is completely created.

**Comment by lstipakov** [comment] 2020-09-02 13:12
@rozmansi I don't think that missing delay is the issue - I added messagebox which shows netsh command line and waits for user action (press OK). After pressing OK problem still reproduces.

**Comment by rozmansi** [comment] 2020-09-02 13:27
Bummer. If we are to drop adapter naming, I need to revise the MSI upgrade logic... Failure to detect exactly named adapters on upgrade would create new adapters.

**Comment by selvanair** [comment] 2020-09-02 13:32
> Bummer. If we are to drop adapter naming, I need to revise the MSI upgrade logic... Failure to detect exactly named adapters on upgrade would create new adapters.

Using the name to detect that anyway is a weak logic -- I always rename adapters, and I guess many do.

**Comment by mattock** [comment] 2020-09-02 13:35
There seem to be "something" on my system called "OpenVPN Wintun" that prevents the rename. Manually renaming to, say, "OpenVPN Wintun LOL" works. That something is not a hidden adapter as `Get-NetAdapter -IncludeHidden` does not show it.

Perhaps we could check what registry calls "Rename-Netadapter" or "netsh interface set interface" are doing and figure out what the culprit is?

**Comment by rozmansi** [comment] 2020-09-02 14:10
> 
> 
> > Bummer. If we are to drop adapter naming, I need to revise the MSI upgrade logic... Failure to detect exactly named adapters on upgrade would create new adapters.
> 
> Using the name to detect that anyway is a weak logic -- I always rename adapters, and I guess many do.

I agree it's not best. It was an intention to get consistent out-of-the-box OpenVPN experience.

Right, let's drop the adapter naming and reduce the setup/upgrade logic to create a new adapter only if there are no adapters for the given device class present yet.

Will prepare a patch the following days.

**Comment by rozmansi** [comment] 2020-09-02 14:13
> 
> 
> There seem to be "something" on my system called "OpenVPN Wintun" that prevents the rename. Manually renaming to, say, "OpenVPN Wintun LOL" works. That something is not a hidden adapter as `Get-NetAdapter -IncludeHidden` does not show it.
> 
> Perhaps we could check what registry calls "Rename-Netadapter" or "netsh interface set interface" are doing and figure out what the culprit is?

You are right... Windows do keep "phantom" adapters in the registry. You won't find them unless you start regedit.exe as TrustedInstaller user.

I guess your Windows 10 has been around a while. The Windows 10 2004 upgrade is known to "backup" network adapters and don't restore them after the upgrade is complete.

**Comment by rozmansi** [comment] 2020-09-02 14:15
The OpenVPN MSIs are finally getting proper real-world testing. :)

**Comment by selvanair** [comment] 2020-09-02 14:35
@rozmansi We also have a problem with additional adapters created by tapctl.exe not completely setup (https://community.openvpn.net/openvpn/ticket/1321) My tests show this is because the driver store where the msi copies the driver files to has limited access for admin -- no idea why would it need more than read access.

**Comment by rozmansi** [comment] 2020-09-03 13:58
> > Using the name to detect that anyway is a weak logic -- I always rename adapters, and I guess many do.
> 
> I agree it's not best. It was an intention to get consistent out-of-the-box OpenVPN experience.
> 
> Right, let's drop the adapter naming and reduce the setup/upgrade logic to create a new adapter only if there are no adapters for the given device class present yet.

I correct myself. The adapters in `TUNTAPAdapter` MSI table are already conditionalized to install only if there are no TUN/TAP adapters installed yet. Upgrades should not mess with existing TUN adapter user setup.

> Will prepare a patch the following days.

After Lev's v2 patch to make adapter renaming non-fatal, no other changes are required IMHO. https://patchwork.openvpn.net/patch/1411/ should fix this issue.

**Comment by selvanair** [comment] 2020-09-03 17:49
> I correct myself. The adapters in TUNTAPAdapter MSI table are already conditionalized to install only if there are no TUN/TAP adapters installed yet. Upgrades should not mess with existing TUN adapter user setup.

What happens when an adapter exists and the driver is updated. Does it get the driver update? If old adapters continue to use an old driver, creating new one's with the latest driver will fail (unless forced as devcon does which we should avoid).

**Comment by lstipakov** [comment] 2020-09-22 14:44
Shall we close this? Renaming is not fatal starting from beta3.

**Closed** 2020-09-23 17:04 UTC
